#include "signum.h"

extern keymap_config_t keymap_config;

#define _QWERTY 0
#define _LOWER 1

enum custom_keycodes {
  QWERTY = SAFE_RANGE,
  LOWER,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

  [_QWERTY] = LAYOUT(
	 KC_MINS, KC_1, KC_2, KC_3, KC_4, KC_7, KC_8, KC_9, KC_0, KC_EQL, 
	 KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_U, KC_I, KC_O, KC_P, KC_BSPC, 
	 KC_LALT, KC_A, KC_S, KC_D, KC_F, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, 
	 KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_ENT, 
	 KC_SPC, KC_LCTL, KC_LALT, KC_LGUI, KC_Q, KC_A, KC_B, KC_C, KC_D, RESET, 
	 MO(1), KC_B, KC_G, KC_T, KC_5, KC_6, KC_Y, KC_H, KC_N, KC_SPC),

  [_LOWER] = LAYOUT(
	 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
	 KC_TRNS, KC_ESC, KC_TRNS, KC_ENT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
	 KC_TRNS, KC_TRNS, KC_TAB, KC_TRNS, KC_TRNS, KC_DOWN, KC_UP, KC_RGHT, KC_TRNS, KC_TRNS, 
	 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_BSPC, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
	 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
	 MO(1), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LEFT, KC_DEL, KC_TRNS),
};
